import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-white dark:bg-black">
        {/* <FirebaseAuthProvider> */}
        {/* <SubscriptionProvider> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          <div className="flex-1 w-full flex flex-col max-w-6xl mx-auto">
            {children}
          </div>


          <Toaster />
        </ThemeProvider>
        {/* </SubscriptionProvider> */}
        {/* </FirebaseAuthProvider> */}
      </body>
    </html>
  );
}
